title:  A-J Mäki, PhD & Hobby Scientist # Antti-Juhana Mäki, PhD
logo: "https://anahill.github.io/pics/headshot_circle_ajm.png"
description: Former postdoc, current hobby scientist
show_downloads: true
theme: jekyll-theme-minimal
include: ["style.css"]
# markdown: GFM
