title:  A-J Mäki, PhD
logo: "https://anahill.github.io/pics/headshot_circle_ajm.png"
description: Data Engineer & Life-Long Researcher, Former Postdoc
show_downloads: true
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme